#include "app/ApplicationController.h"
#include "core/SettingsStore.h"
#include "ui/Localization.h"
#include "ui/BusyDialog.h"
#include "ui/MainPanel.h"
#include "ui/TrayIcon.h"
#include "ui/UiStyle.h"
#include "ui/WelcomeDialog.h"
#include "FakePlatform.h"
#ifdef Q_OS_WIN
#include "platform/windows/WindowsTrayIntegration.h"
#endif

#include <QCheckBox>
#include <QComboBox>
#include <QDir>
#include <QElapsedTimer>
#include <QFontDatabase>
#include <QFontInfo>
#include <QLabel>
#include <QImage>
#include <QPainter>
#include <QScrollArea>
#include <QScrollBar>
#include <QScreen>
#include <QPushButton>
#include <QSlider>
#include <QTemporaryDir>
#include <QSystemTrayIcon>
#include <QWheelEvent>
#include <QWindow>
#include <QtTest>

using namespace eink;
using namespace eink::tests;

class E2ETests : public QObject {
    Q_OBJECT
private slots:
    void completeUserJourney();
    void windows7CapabilityPath();
    void windows10CompatibilityColorPath();
    void olderWindowsUsesNightLightSettingsFallback();
    void nightLightSwitchSynchronizesWithSystem();
    void welcomeFlowPersistsChoice();
    void stateChangesDoNotRebuildWholePanel();
    void wheelOverSliderScrollsPanelOnly();
    void minimizeAndFocusLossHidePanel();
    void cjkLanguagesUseWindowsUiFonts();
    void busyIndicatorAnimates();
    void hotplugThenOpenPanelIsStable();
    void trayUsesBookPagesGlyph();
    void windows10TrayPromotionFindsOwnIcon();
    void processingIndicatorStaysInsideMainWindow();
    void displaySelectorsUseVectorIcons();
    void firstShowBindsToRequestedScreen();
    void widerLayoutKeepsLabelsVisible();
    void modeButtonsAreContinuousAndPanelUsesScreenHeight();
    void rgbDisclosureAndSwitchCornersUseVectorPainting();
    void fastOperationsDoNotFlashProcessingIndicator();
    void mouseClicksDoNotLeaveFocusFrames();
    void mainPanelUsesQtRoundedCorners();
    void slowSystemTogglesUseLocalSpinner();
};

void E2ETests::completeUserJourney(){QTemporaryDir dir;const QString path=dir.filePath(QStringLiteral("settings.ini"));auto fake=std::make_unique<FakePlatform>();FakePlatform *raw=fake.get();ApplicationController controller(std::move(fake),SettingsStore(path));controller.initialize();QSignalSpy operationStarted(&controller,&ApplicationController::operationStarted);QSignalSpy operationFinished(&controller,&ApplicationController::operationFinished);MainPanel panel(&controller);panel.show();QTest::qWait(50);
    QCheckBox *eink=nullptr;for(QCheckBox *candidate:panel.findChildren<QCheckBox*>(QStringLiteral("eink-checkbox")))if(candidate->property("displayId").toString()==QStringLiteral("fake-external"))eink=candidate;QVERIFY(eink);eink->click();QTRY_VERIFY(controller.settingsFor(QStringLiteral("fake-external")).isEink);QVERIFY(raw->effectsReduced);QCoreApplication::processEvents();
    auto *visualEffects=panel.findChild<QAbstractButton*>(QStringLiteral("visual-effects-switch"));auto *follow=panel.findChild<QAbstractButton*>(QStringLiteral("auto-visual-effects-switch"));auto *night=panel.findChild<QAbstractButton*>(QStringLiteral("disable-night-light-switch"));auto *lightMode=panel.findChild<QAbstractButton*>(QStringLiteral("windows-light-mode-switch"));QVERIFY(visualEffects);QVERIFY(follow);QVERIFY(night);QVERIFY(lightMode);QVERIFY(!night->isChecked());QVERIFY(follow->y()>visualEffects->y());QVERIFY(night->mapTo(&panel,QPoint()).y()>follow->mapTo(&panel,QPoint()).y());QVERIFY(lightMode->mapTo(&panel,QPoint()).y()>night->mapTo(&panel,QPoint()).y());night->click();night->click();night->click();QCOMPARE(raw->nightDisableCalls,0);QTest::qWait(280);QVERIFY(raw->nightDisabled);QCOMPARE(raw->nightDisableCalls,1);night->click();QTest::qWait(280);QVERIFY(!raw->nightDisabled);QVERIFY(raw->nightLightEnabled());night->click();QTest::qWait(280);QVERIFY(raw->nightDisabled);lightMode->click();QTRY_VERIFY(raw->lightMode);QCOMPARE(raw->lightModeCalls,1);
    QVERIFY(!panel.findChild<QAbstractButton*>(QStringLiteral("shaking-switch")));
    QVERIFY(!panel.findChild<QPushButton*>(QStringLiteral("night-light-button")));
    auto *anime=panel.findChild<QPushButton*>(QStringLiteral("preset-anime"));QVERIFY(anime&&anime->isEnabled());anime->click();QCOMPARE(controller.settingsFor(QStringLiteral("fake-external")).saturation,2.0);QCOMPARE(panel.findChild<QSlider*>(QStringLiteral("saturation-slider"))->value(),200);QTRY_VERIFY(raw->colorApplyCalls>0);
    auto *rgbToggle=panel.findChild<QPushButton*>(QStringLiteral("rgb-toggle"));QVERIFY(rgbToggle);rgbToggle->click();QCoreApplication::processEvents();auto *red=panel.findChild<QSlider*>(QStringLiteral("rgb-red"));auto *rgbReset=panel.findChild<QPushButton*>(QStringLiteral("rgb-reset"));QVERIFY(red);QVERIFY(rgbReset);red->setValue(120);QVERIFY(rgbReset->isEnabled());QMetaObject::invokeMethod(red,"sliderReleased",Qt::DirectConnection);QCoreApplication::processEvents();QCOMPARE(controller.settingsFor(QStringLiteral("fake-external")).rgb.red,1.2);rgbReset->click();QVERIFY(controller.settingsFor(QStringLiteral("fake-external")).rgb.isIdentity());QCOMPARE(panel.findChild<QSlider*>(QStringLiteral("rgb-red"))->value(),100);QCOMPARE(panel.findChild<QSlider*>(QStringLiteral("rgb-green"))->value(),100);QCOMPARE(panel.findChild<QSlider*>(QStringLiteral("rgb-blue"))->value(),100);QVERIFY(!rgbReset->isEnabled());
    QVERIFY(panel.findChild<QLabel*>(QStringLiteral("text-caption")));QVERIFY(panel.findChild<QLabel*>(QStringLiteral("video-caption")));auto *solid=panel.findChild<QPushButton*>(QStringLiteral("text-solid"));QVERIFY(solid);solid->click();QCOMPARE(controller.settingsFor(QStringLiteral("fake-external")).textLevel,TextLevel::Solid);QCoreApplication::processEvents();auto *detail=panel.findChild<QLabel*>(QStringLiteral("text-detail"));auto *blocked=panel.findChild<QLabel*>(QStringLiteral("video-blocked"));QVERIFY(detail);QVERIFY(blocked);QCOMPARE(detail->text(),L("text.detail.solid"));QCOMPARE(blocked->text(),L("video.blocked"));auto *helperArea=panel.findChild<QScrollArea*>();QVERIFY(helperArea);helperArea->ensureWidgetVisible(blocked,20,20);QCoreApplication::processEvents();QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(panel.grab().save(QStringLiteral("artifacts/e2e-text-helper.png")));
    auto *medium=panel.findChild<QPushButton*>(QStringLiteral("video-medium"));QVERIFY(medium);medium->click();QCOMPARE(controller.settingsFor(QStringLiteral("fake-external")).enhanceLevel,EnhanceLevel::Medium);QCOMPARE(controller.settingsFor(QStringLiteral("fake-external")).textLevel,TextLevel::Off);QCoreApplication::processEvents();auto *warning=panel.findChild<QLabel*>(QStringLiteral("video-warning"));QVERIFY(warning);QVERIFY(warning->text().contains(L("cost.34")));helperArea->ensureWidgetVisible(warning,20,20);QCoreApplication::processEvents();QVERIFY(panel.grab().save(QStringLiteral("artifacts/e2e-video-warning.png")));
    auto *advanced=panel.findChild<QAbstractButton*>(QStringLiteral("advanced-switch"));QVERIFY(advanced);advanced->click();QTRY_VERIFY(controller.settingsFor(QStringLiteral("fake-external")).advanced);QCoreApplication::processEvents();auto *gamma=panel.findChild<QSlider*>(QStringLiteral("curve-gamma"));QVERIFY(gamma);gamma->setValue(214);QMetaObject::invokeMethod(gamma,"sliderReleased",Qt::DirectConnection);QCOMPARE(controller.settingsFor(QStringLiteral("fake-external")).customCurve.gamma,2.14);
    QCoreApplication::processEvents();auto *slot=panel.findChild<QPushButton*>(QStringLiteral("curve-slot-1"));QVERIFY(slot);slot->click();QVERIFY(controller.settings().savedCurves[0].occupied);
    QCoreApplication::processEvents();auto *login=panel.findChild<QAbstractButton*>(QStringLiteral("launch-login-switch"));QVERIFY(login);login->click();QVERIFY(controller.settings().launchAtLogin);QVERIFY(raw->login);
    controller.waitForPendingOperations();QCoreApplication::processEvents();QVERIFY(operationStarted.count()>0);QCOMPARE(operationStarted.count(),operationFinished.count());QDir().mkpath(QStringLiteral("artifacts"));panel.grab().save(QStringLiteral("artifacts/e2e-main.png"));controller.shutdown();QVERIFY(raw->shutDown);QVERIFY(!raw->nightDisabled);QVERIFY(raw->lightMode);SettingsStore reload(path);AppSettings saved=reload.load();QVERIFY(saved.forDisplay(QStringLiteral("fake-external")).advanced);QCOMPARE(saved.forDisplay(QStringLiteral("fake-external")).saturation,2.0);}

void E2ETests::windows7CapabilityPath(){QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>(false,false);ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("s.ini"))));controller.initialize();MainPanel panel(&controller);panel.show();QCheckBox *eink=nullptr;for(QCheckBox *candidate:panel.findChildren<QCheckBox*>(QStringLiteral("eink-checkbox")))if(candidate->property("displayId").toString()==QStringLiteral("fake-external"))eink=candidate;QVERIFY(eink);eink->click();QCoreApplication::processEvents();QVERIFY(!panel.findChild<QSlider*>(QStringLiteral("saturation-slider")));QVERIFY(!panel.findChild<QPushButton*>(QStringLiteral("rgb-toggle")));QVERIFY(!panel.findChild<QAbstractButton*>(QStringLiteral("windows-light-mode-switch")));QVERIFY(!panel.findChild<QAbstractButton*>(QStringLiteral("disable-night-light-switch")));QVERIFY(!panel.findChild<QPushButton*>(QStringLiteral("night-light-button")));QVERIFY(!panel.findChild<QLabel*>(QStringLiteral("night-light-fallback-recommendation")));QVERIFY(!panel.findChild<QLabel*>(QStringLiteral("night-light-settings-path")));QVERIFY(!panel.findChild<QAbstractButton*>(QStringLiteral("shaking-switch")));auto *text=panel.findChild<QPushButton*>(QStringLiteral("text-medium"));QVERIFY(text&&text->isEnabled());QWidget *card=eink;while(card&&card->objectName()!=QStringLiteral("displayCard"))card=card->parentWidget();QVERIFY(card);QTRY_VERIFY(card->height()>300);text->click();QCOMPARE(controller.settingsFor(QStringLiteral("fake-external")).textLevel,TextLevel::Medium);QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(panel.grab().save(QStringLiteral("artifacts/e2e-windows7-gated.png")));controller.shutdown();}

void E2ETests::windows10CompatibilityColorPath(){QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();FakePlatform *raw=fake.get();raw->displayList[0].acmSupported=false;raw->displayList[0].acmEnabled=false;raw->displayList[0].colorAdjustmentSupported=true;raw->displayList[0].usesWindows10Mhc2=true;ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("windows10.ini"))));controller.initialize();controller.setEink(QStringLiteral("fake-external"),true);controller.waitForPendingOperations();MainPanel panel(&controller);panel.show();QCoreApplication::processEvents();QVERIFY(panel.findChild<QSlider*>(QStringLiteral("saturation-slider")));QVERIFY(panel.findChild<QPushButton*>(QStringLiteral("rgb-toggle")));auto *note=panel.findChild<QLabel*>(QStringLiteral("saturation-pipeline-note"));QVERIFY(note);QCOMPARE(note->text(),L("saturation.mhc2.compat"));QVERIFY(raw->colorApplyCalls>0);controller.shutdown();}

void E2ETests::olderWindowsUsesNightLightSettingsFallback(){QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>(true,true,false);FakePlatform *raw=fake.get();ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("fallback.ini"))));controller.initialize();controller.settingsFor(QStringLiteral("fake-external")).isEink=true;MainPanel panel(&controller);panel.show();QCoreApplication::processEvents();QVERIFY(!panel.findChild<QAbstractButton*>(QStringLiteral("disable-night-light-switch")));auto *open=panel.findChild<QPushButton*>(QStringLiteral("night-light-button"));auto *recommendation=panel.findChild<QLabel*>(QStringLiteral("night-light-fallback-recommendation"));auto *path=panel.findChild<QLabel*>(QStringLiteral("night-light-settings-path"));QVERIFY(open);QVERIFY(recommendation);QVERIFY(path);QCOMPARE(path->text(),L("night.fallback.path"));QCOMPARE(panel.findChildren<QPushButton*>(QStringLiteral("night-light-button")).size(),1);QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(panel.grab().save(QStringLiteral("artifacts/e2e-night-light-settings-fallback.png")));open->click();QCOMPARE(raw->openedNightLight,1);controller.shutdown();}

void E2ETests::nightLightSwitchSynchronizesWithSystem(){QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();FakePlatform *raw=fake.get();raw->nightDisabled=true;ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("sync.ini"))));controller.initialize();MainPanel panel(&controller);panel.show();QCoreApplication::processEvents();auto *toggle=panel.findChild<QAbstractButton*>(QStringLiteral("disable-night-light-switch"));auto *status=panel.findChild<QLabel*>(QStringLiteral("disable-night-light-status"));auto *warning=panel.findChild<QLabel*>(QStringLiteral("night-light-warning"));QVERIFY(toggle);QVERIFY(status);QVERIFY(warning);QVERIFY(toggle->isChecked());QCOMPARE(status->text(),L("system.on"));QVERIFY(!warning->isVisible());raw->nightDisabled=false;controller.refreshNightLightState();QCoreApplication::processEvents();QVERIFY(!toggle->isChecked());QCOMPARE(status->text(),L("system.off"));QVERIFY(warning->isVisible());QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(panel.grab().save(QStringLiteral("artifacts/e2e-night-light-warning.png")));raw->nightDisabled=true;controller.refreshNightLightState();QCoreApplication::processEvents();QVERIFY(toggle->isChecked());QCOMPARE(status->text(),L("system.on"));QVERIFY(!warning->isVisible());controller.shutdown();}

void E2ETests::welcomeFlowPersistsChoice(){QTemporaryDir dir;const QString path=dir.filePath(QStringLiteral("s.ini"));auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(path));controller.initialize();QVERIFY(!controller.settings().trayDiscoveryShown);controller.setTrayDiscoveryShown(true);WelcomeDialog welcome(&controller);QVERIFY(welcome.windowFlags().testFlag(Qt::FramelessWindowHint));QVERIFY(welcome.windowFlags().testFlag(Qt::WindowStaysOnTopHint));QVERIFY(welcome.testAttribute(Qt::WA_TranslucentBackground));welcome.show();QCoreApplication::processEvents();QVERIFY(welcome.mask().isEmpty());const QImage rendered=welcome.grab().toImage().convertToFormat(QImage::Format_ARGB32);QCOMPARE(qAlpha(rendered.pixel(0,0)),0);QCOMPARE(qAlpha(rendered.pixel(rendered.width()-1,0)),0);QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(welcome.grab().save(QStringLiteral("artifacts/e2e-welcome.png")));auto *hide=welcome.findChild<QCheckBox*>(QStringLiteral("welcome-hide"));auto *done=welcome.findChild<QPushButton*>(QStringLiteral("welcome-done"));QVERIFY(hide);QVERIFY(done);hide->setChecked(true);done->click();QVERIFY(!controller.settings().showWelcome);AppSettings saved=SettingsStore(path).load();QVERIFY(!saved.showWelcome);QVERIFY(saved.trayDiscoveryShown);controller.shutdown();}

void E2ETests::stateChangesDoNotRebuildWholePanel(){QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("s.ini"))));controller.initialize();controller.setEink(QStringLiteral("fake-external"),true);MainPanel panel(&controller);panel.show();QCoreApplication::processEvents();auto *visual=panel.findChild<QAbstractButton*>(QStringLiteral("visual-effects-switch"));auto *anime=panel.findChild<QPushButton*>(QStringLiteral("preset-anime"));QVERIFY(visual);QVERIFY(anime);QElapsedTimer timer;timer.start();anime->click();QCoreApplication::processEvents();QVERIFY2(timer.elapsed()<1000,"A simple preset interaction blocked the UI test for over one second");QCOMPARE(panel.findChild<QAbstractButton*>(QStringLiteral("visual-effects-switch")),visual);controller.shutdown();}

void E2ETests::wheelOverSliderScrollsPanelOnly(){QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("s.ini"))));controller.initialize();controller.setEink(QStringLiteral("fake-external"),true);MainPanel panel(&controller);panel.show();QCoreApplication::processEvents();auto *saturation=panel.findChild<QSlider*>(QStringLiteral("saturation-slider"));auto *area=panel.findChild<QScrollArea*>();QVERIFY(saturation);QVERIFY(area);auto *bar=area->verticalScrollBar();bar->setValue(0);const int sliderBefore=saturation->value();const QPointF local=saturation->rect().center();const QPointF global=saturation->mapToGlobal(local.toPoint());QWheelEvent wheel(local,global,QPoint(),QPoint(0,-120),Qt::NoButton,Qt::NoModifier,Qt::NoScrollPhase,false);QApplication::sendEvent(saturation,&wheel);QCoreApplication::processEvents();QCOMPARE(saturation->value(),sliderBefore);QVERIFY(bar->value()>0);controller.shutdown();}

void E2ETests::minimizeAndFocusLossHidePanel(){QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("s.ini"))));controller.initialize();MainPanel panel(&controller);QSignalSpy quitSpy(&panel,&MainPanel::quitRequested);panel.show();QCoreApplication::processEvents();auto *minimize=panel.findChild<QPushButton*>(QStringLiteral("minimize-button"));auto *quit=panel.findChild<QPushButton*>(QStringLiteral("quit-button"));QVERIFY(minimize);QVERIFY(quit);QCOMPARE(minimize->text(),QStringLiteral("−"));QVERIFY(minimize->x()<quit->x());minimize->click();QVERIFY(!panel.isVisible());QCOMPARE(quitSpy.count(),0);panel.show();QCoreApplication::processEvents();panel.setConfigurationBusy(true);QEvent busyDeactivated(QEvent::WindowDeactivate);QApplication::sendEvent(&panel,&busyDeactivated);QTest::qWait(80);QVERIFY(panel.isVisible());panel.setConfigurationBusy(false);auto *languages=panel.findChild<QComboBox*>(QStringLiteral("language-combo"));QVERIFY(languages);languages->showPopup();QTRY_VERIFY(QApplication::activePopupWidget());QEvent popupDeactivated(QEvent::WindowDeactivate);QApplication::sendEvent(&panel,&popupDeactivated);QTest::qWait(80);QVERIFY(panel.isVisible());languages->hidePopup();QCoreApplication::processEvents();QApplication::setActiveWindow(nullptr);QEvent deactivated(QEvent::WindowDeactivate);QApplication::sendEvent(&panel,&deactivated);QTRY_VERIFY(!panel.isVisible());QCOMPARE(quitSpy.count(),0);controller.shutdown();}

void E2ETests::cjkLanguagesUseWindowsUiFonts(){
    if(QGuiApplication::platformName()==QStringLiteral("offscreen"))QSKIP("The offscreen Qt plugin does not enumerate Windows system fonts.");
    QString baseStyle=QApplication::style()->objectName();if(baseStyle.isEmpty())baseStyle=QStringLiteral("windowsvista");QApplication::setStyle(new ui::SmoothProxyStyle(baseStyle));
    Localization::instance().setLanguage(QStringLiteral("zh-Hans"));QVERIFY(QApplication::font().family()==QStringLiteral("Microsoft YaHei UI")||QApplication::font().family()==QStringLiteral("Microsoft YaHei"));QCOMPARE(QFontInfo(QApplication::font()).family(),QApplication::font().family());
    Localization::instance().setLanguage(QStringLiteral("zh-Hant"));QVERIFY(QApplication::font().family()==QStringLiteral("Microsoft JhengHei UI")||QApplication::font().family()==QStringLiteral("Microsoft JhengHei"));QCOMPARE(QFontInfo(QApplication::font()).family(),QApplication::font().family());
    Localization::instance().setLanguage(QStringLiteral("ja"));QVERIFY(QApplication::font().family()==QStringLiteral("Yu Gothic UI")||QApplication::font().family()==QStringLiteral("Meiryo UI")||QApplication::font().family()==QStringLiteral("Meiryo"));QCOMPARE(QFontInfo(QApplication::font()).family(),QApplication::font().family());
    QVERIFY((QApplication::font().styleStrategy()&QFont::PreferAntialias)!=0);QCOMPARE(QApplication::font().hintingPreference(),QFont::PreferNoHinting);
    Localization::instance().setLanguage(QStringLiteral("en"));QCOMPARE(QApplication::font().family(),QStringLiteral("Segoe UI"));QCOMPARE(QFontInfo(QApplication::font()).family(),QApplication::font().family());
    auto capture=[](const QString &language,const QString &fileName){QTemporaryDir dir;const QString path=dir.filePath(QStringLiteral("language.ini"));AppSettings settings;settings.language=language;SettingsStore(path).save(settings);auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(path));controller.initialize();MainPanel panel(&controller);panel.show();QCoreApplication::processEvents();QDir().mkpath(QStringLiteral("artifacts"));const bool saved=panel.grab().save(QStringLiteral("artifacts/")+fileName);controller.shutdown();return saved;};
    QVERIFY(capture(QStringLiteral("zh-Hans"),QStringLiteral("e2e-cjk.png")));QVERIFY(capture(QStringLiteral("zh-Hant"),QStringLiteral("e2e-zh-Hant.png")));QVERIFY(capture(QStringLiteral("ja"),QStringLiteral("e2e-ja.png")));
    Localization::instance().setLanguage(QStringLiteral("en"));
}

void E2ETests::busyIndicatorAnimates(){BusyDialog busy;busy.setMessage(L("busy.configuring"));busy.showCentered();QCoreApplication::processEvents();auto *spinner=busy.findChild<QWidget*>(QStringLiteral("busy-spinner"));auto *message=busy.findChild<QLabel*>(QStringLiteral("busy-message"));QVERIFY(spinner);QVERIFY(message);QCOMPARE(message->text(),L("busy.configuring"));QVERIFY(busy.testAttribute(Qt::WA_TranslucentBackground));QVERIFY(busy.mask().isEmpty());const QImage rendered=busy.grab().toImage().convertToFormat(QImage::Format_ARGB32);QCOMPARE(qAlpha(rendered.pixel(0,0)),0);QVERIFY(qAlpha(rendered.pixel(rendered.width()/2,rendered.height()/2))>250);const int before=spinner->property("angle").toInt();QTest::qWait(180);QVERIFY(spinner->property("angle").toInt()!=before);QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(busy.grab().save(QStringLiteral("artifacts/e2e-configuring.png")));busy.hide();}

void E2ETests::hotplugThenOpenPanelIsStable(){QTemporaryDir dir;const QString path=dir.filePath(QStringLiteral("hotplug.ini"));auto fake=std::make_unique<FakePlatform>();FakePlatform *raw=fake.get();const DisplayInfo external=raw->displayList.front();raw->displayList.removeFirst();AppSettings settings;auto &externalSettings=settings.forDisplay(external.stableId);externalSettings.isEink=true;externalSettings.saturation=1.3;SettingsStore(path).save(settings);ApplicationController controller(std::move(fake),SettingsStore(path));controller.initialize();MainPanel panel(&controller);for(int i=0;i<20;++i){if(i%2==0)raw->displayList.prepend(external);else raw->displayList.removeFirst();controller.refreshDisplays();}raw->displayList.prepend(external);controller.refreshDisplays();controller.reapplyAll();QCoreApplication::processEvents();panel.showPanel();QCoreApplication::processEvents();int matches=0;for(QCheckBox *box:panel.findChildren<QCheckBox*>(QStringLiteral("eink-checkbox")))if(box->property("displayId").toString()==external.stableId)++matches;QCOMPARE(matches,1);QCOMPARE(controller.displays().size(),2);QTRY_VERIFY(raw->colorApplyCalls>0);controller.shutdown();}

void E2ETests::trayUsesBookPagesGlyph(){
    const QImage light=ui::bookPagesTrayImage(48,true).convertToFormat(QImage::Format_ARGB32);
    const QImage dark=ui::bookPagesTrayImage(48,false).convertToFormat(QImage::Format_ARGB32);
    int blackPixels=0,whitePixels=0;
    for(int y=0;y<48;++y)for(int x=0;x<48;++x){const QRgb a=light.pixel(x,y),b=dark.pixel(x,y);if(qAlpha(a)>160&&qGray(a)<64)++blackPixels;if(qAlpha(b)>160&&qGray(b)>192)++whitePixels;}
    QVERIFY(blackPixels>100);QVERIFY(whitePixels>100);QCOMPARE(qAlpha(light.pixel(0,0)),0);QCOMPARE(qAlpha(dark.pixel(47,47)),0);
    QImage preview(128,64,QImage::Format_ARGB32);preview.fill(Qt::white);QPainter painter(&preview);painter.fillRect(64,0,64,64,QColor(32,32,32));painter.drawImage(8,8,light);painter.drawImage(72,8,dark);painter.end();QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(preview.save(QStringLiteral("artifacts/e2e-tray-book-pages.png")));
}

void E2ETests::windows10TrayPromotionFindsOwnIcon(){
#ifdef Q_OS_WIN
    if(QGuiApplication::platformName()!=QStringLiteral("windows"))QSKIP("A real Windows notification area is required.");
    if(!QSystemTrayIcon::isSystemTrayAvailable())QSKIP("The Windows notification area is unavailable.");
    QSystemTrayIcon tray(ui::bookPagesTrayIcon(ui::systemTrayUsesLightBackground()));
    tray.setToolTip(QStringLiteral("E-Ink Assistant Windows 10 tray compatibility test"));
    tray.show();
    windows::TrayPromotionResult result=windows::TrayPromotionResult::Pending;
    for(int attempt=0;attempt<12&&result==windows::TrayPromotionResult::Pending;++attempt){QTest::qWait(150);result=windows::promoteOwnTrayIcon();}
    qInfo().noquote()<<windows::trayIntegrationDiagnostic();
    QVERIFY(result==windows::TrayPromotionResult::Promoted||result==windows::TrayPromotionResult::Overflow);
    if(result==windows::TrayPromotionResult::Promoted)QTRY_VERIFY_WITH_TIMEOUT(!windows::ownPromotedTrayIconRects().isEmpty(),2000);
    else QVERIFY(windows::ownTrayIconInOverflow());
    tray.hide();
#else
    QSKIP("Windows-only tray test.");
#endif
}

void E2ETests::processingIndicatorStaysInsideMainWindow(){
    QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("busy.ini"))));controller.initialize();MainPanel panel(&controller);panel.show();QCoreApplication::processEvents();panel.setConfigurationBusy(true,L("busy.configuring"));QCoreApplication::processEvents();
    auto *indicator=panel.findChild<QWidget*>(QStringLiteral("inline-processing"));auto *message=panel.findChild<QLabel*>(QStringLiteral("inline-processing-message"));auto *spinner=panel.findChild<QWidget*>(QStringLiteral("inline-processing-spinner"));QVERIFY(indicator);QVERIFY(message);QVERIFY(spinner);QVERIFY(indicator->isVisible());QCOMPARE(indicator->window(),static_cast<QWidget*>(&panel));QCOMPARE(message->text(),L("busy.configuring"));QCOMPARE(panel.cursor().shape(),Qt::ArrowCursor);
    for(QWidget *top:QApplication::topLevelWidgets())QVERIFY2(!(top->objectName()==QStringLiteral("busy-dialog")&&top->isVisible()),"Configuration opened a separate busy window");
    const QImage indicatorImage=indicator->grab().toImage().convertToFormat(QImage::Format_ARGB32);const QPoint clearSample=spinner->mapTo(indicator,QPoint(1,1));const QColor clearColor=indicatorImage.pixelColor(clearSample);QVERIFY2(clearColor.red()>=235&&clearColor.red()<252&&clearColor.red()==clearColor.green()&&clearColor.green()==clearColor.blue(),qPrintable(QStringLiteral("Spinner corner was not transparent over the processing pill: %1").arg(clearColor.name())));
    const int before=spinner->property("angle").toInt();QTest::qWait(180);QVERIFY(spinner->property("angle").toInt()!=before);QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(panel.grab().save(QStringLiteral("artifacts/e2e-inline-processing.png")));panel.setConfigurationBusy(false);QVERIFY(!indicator->isVisible());controller.shutdown();
}

void E2ETests::displaySelectorsUseVectorIcons(){
    QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("selectors.ini"))));controller.initialize();controller.settingsFor(QStringLiteral("fake-external")).isEink=true;MainPanel panel(&controller);panel.show();QCoreApplication::processEvents();const auto boxes=panel.findChildren<QCheckBox*>(QStringLiteral("eink-checkbox"));QCOMPARE(boxes.size(),2);bool foundChecked=false,foundUnchecked=false;for(QCheckBox *box:boxes){QVERIFY(!box->text().contains(QChar(0x25A3)));QVERIFY(!box->text().contains(QChar(0x25B0)));QVERIFY(box->minimumHeight()>=42);foundChecked|=box->isChecked();foundUnchecked|=!box->isChecked();}QVERIFY(foundChecked);QVERIFY(foundUnchecked);QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(panel.grab().save(QStringLiteral("artifacts/e2e-display-selectors.png")));controller.shutdown();
}

void E2ETests::firstShowBindsToRequestedScreen(){
    const auto screens=QGuiApplication::screens();if(screens.size()<2)QSKIP("Mixed-monitor placement requires at least two active screens.");
    QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("placement.ini"))));controller.initialize();MainPanel panel(&controller);
    QScreen *first=screens.first();QScreen *second=screens.last();panel.showPanel(first);QTRY_COMPARE(panel.windowHandle()->screen(),first);QVERIFY(first->availableGeometry().contains(panel.frameGeometry().center()));panel.hide();QCoreApplication::processEvents();
    panel.showPanel(second);QTRY_COMPARE(panel.windowHandle()->screen(),second);QTest::qWait(120);const QRect panelRect=panel.frameGeometry(),targetRect=second->availableGeometry();QVERIFY2(targetRect.contains(panelRect.center()),qPrintable(QStringLiteral("Panel center %1,%2 was outside %3 on %4 (DPR %5)").arg(panelRect.center().x()).arg(panelRect.center().y()).arg(second->name()).arg(targetRect.width()).arg(second->devicePixelRatio())));panel.hide();controller.shutdown();
}

void E2ETests::widerLayoutKeepsLabelsVisible(){
    if(QGuiApplication::platformName()==QStringLiteral("offscreen"))QSKIP("Native font metrics and size-hint propagation are required for clipping checks.");Localization::instance().setLanguage(QStringLiteral("en"));QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("wide.ini"))));controller.initialize();controller.settingsFor(QStringLiteral("fake-external")).isEink=true;MainPanel panel(&controller);panel.show();QCoreApplication::processEvents();QCOMPARE(panel.width(),680);
    QLabel *visualTitle=nullptr;for(QLabel *candidate:panel.findChildren<QLabel*>())if(candidate->text()==L("system.title")){visualTitle=candidate;break;}QVERIFY(visualTitle);const QFontMetrics titleMetrics(visualTitle->font());QVERIFY2(!visualTitle->wordWrap(),"Reduce Transparency & Motion was still configured to wrap");QVERIFY2(titleMetrics.horizontalAdvance(visualTitle->text())<=visualTitle->width(),"Reduce Transparency & Motion was horizontally clipped");
    auto *factory=panel.findChild<QPushButton*>(QStringLiteral("preset-factory"));QVERIFY(factory);factory->click();QCoreApplication::processEvents();QVERIFY(factory->isChecked());QCOMPARE(factory->property("selected-font-weight").toInt(),static_cast<int>(QFont::Black));QFont checkedFont=factory->font();checkedFont.setWeight(QFont::Black);QVERIFY2(QFontMetrics(checkedFont).horizontalAdvance(factory->text())+24<=factory->width(),"Heavy Factory label was clipped");QVERIFY2(!panel.findChild<QPushButton*>(QStringLiteral("visual-effects-settings")),"Reduce Transparency & Motion still exposed an unnecessary settings button");for(const char *name:{"preset-bw","preset-faded","preset-factory","preset-enhanced","preset-vivid","preset-anime"}){auto *button=panel.findChild<QPushButton*>(QString::fromLatin1(name));QVERIFY(button);QVERIFY(button->mapTo(&panel,QPoint(button->width(),0)).x()<=panel.width()-16);}QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(panel.grab().save(QStringLiteral("artifacts/e2e-wide-layout.png")));controller.shutdown();
}

void E2ETests::modeButtonsAreContinuousAndPanelUsesScreenHeight(){
    if(QGuiApplication::platformName()==QStringLiteral("offscreen"))QSKIP("Native size-hint propagation is required for content-aware window height checks.");QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("height.ini"))));controller.initialize();controller.settingsFor(QStringLiteral("fake-external")).isEink=true;MainPanel panel(&controller);QScreen *screen=QGuiApplication::primaryScreen();QVERIFY(screen);panel.showPanel(screen);QCoreApplication::processEvents();const QRect available=screen->availableGeometry();QCOMPARE(panel.height(),available.height()-32);QCOMPARE(panel.frameGeometry().top()-available.top(),16);QCOMPARE(available.bottom()-panel.frameGeometry().bottom(),16);
    auto continuous=[&panel](const char *leftName,const char *rightName){auto *left=panel.findChild<QPushButton*>(QString::fromLatin1(leftName));auto *right=panel.findChild<QPushButton*>(QString::fromLatin1(rightName));QVERIFY(left);QVERIFY(right);const int leftRight=left->mapTo(&panel,QPoint(left->width(),0)).x();const int rightLeft=right->mapTo(&panel,QPoint(0,0)).x();QCOMPARE(rightLeft-leftRight,0);QCOMPARE(left->height(),right->height());QVERIFY(left->property("choice-button").toBool());QVERIFY(right->property("choice-button").toBool());};continuous("text-off","text-medium");continuous("text-medium","text-strong");continuous("video-off","video-subtle");continuous("video-subtle","video-medium");
    auto *selected=panel.findChild<QPushButton*>(QStringLiteral("text-off"));auto *unselected=panel.findChild<QPushButton*>(QStringLiteral("text-medium"));QVERIFY(selected&&selected->isChecked());QVERIFY(unselected&&!unselected->isChecked());QCOMPARE(selected->property("selected-font-weight").toInt(),static_cast<int>(QFont::Black));
    auto darkBottomDepth=[](QPushButton *button){const QImage image=button->grab().toImage().convertToFormat(QImage::Format_ARGB32);const int x=image.width()/2;int depth=0;for(int y=image.height()-1;y>=0;--y){if(qGray(image.pixel(x,y))<100)++depth;else if(depth)break;}return depth;};
    QVERIFY2(darkBottomDepth(selected)>=darkBottomDepth(unselected)+2,"Selected segment did not use a distinct thick bottom underline");QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(panel.grab().save(QStringLiteral("artifacts/e2e-continuous-mode-buttons.png")));panel.hide();controller.shutdown();
    auto compactFake=std::make_unique<FakePlatform>();compactFake->displayList.clear();ApplicationController compactController(std::move(compactFake),SettingsStore(dir.filePath(QStringLiteral("compact.ini"))));compactController.initialize();MainPanel compact(&compactController);compact.showPanel(screen);QCoreApplication::processEvents();QVERIFY2(compact.height()<available.height()-32,"A compact panel unnecessarily expanded to maximum screen height");QCOMPARE(available.bottom()-compact.frameGeometry().bottom(),16);compact.hide();compactController.shutdown();
}

void E2ETests::rgbDisclosureAndSwitchCornersUseVectorPainting(){
    QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("vector-controls.ini"))));controller.initialize();controller.settingsFor(QStringLiteral("fake-external")).isEink=true;MainPanel panel(&controller);panel.show();QCoreApplication::processEvents();
    auto *rgb=panel.findChild<QPushButton*>(QStringLiteral("rgb-toggle"));QVERIFY(rgb);QCOMPARE(rgb->text(),L("rgb.title"));QVERIFY(!rgb->text().contains(QChar(0x203A)));QVERIFY(!rgb->text().contains(QChar(0x2304)));QVERIFY(!rgb->property("disclosure-expanded").toBool());rgb->click();QCoreApplication::sendPostedEvents(nullptr,QEvent::DeferredDelete);QCoreApplication::processEvents();rgb=panel.findChild<QPushButton*>(QStringLiteral("rgb-toggle"));QVERIFY(rgb);QCOMPARE(rgb->text(),L("rgb.title"));QVERIFY(rgb->property("disclosure-expanded").toBool());
    auto *toggle=panel.findChild<QAbstractButton*>(QStringLiteral("advanced-switch"));QVERIFY(toggle);QVERIFY(toggle->property("antialiased-corners").toBool());const QImage image=toggle->grab().toImage().convertToFormat(QImage::Format_ARGB32);bool foundAntialiasedEdge=false;for(int y=0;y<image.height()&&!foundAntialiasedEdge;++y)for(int x=0;x<image.width();++x){const QColor pixel=image.pixelColor(x,y);if(pixel.red()==pixel.green()&&pixel.green()==pixel.blue()&&pixel.red()>40&&pixel.red()<240){foundAntialiasedEdge=true;break;}}QVERIFY2(foundAntialiasedEdge,"Switch outline did not contain antialiased edge pixels");
    QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(panel.grab().save(QStringLiteral("artifacts/e2e-vector-controls.png")));controller.shutdown();
}

void E2ETests::fastOperationsDoNotFlashProcessingIndicator(){
    QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("delay.ini"))));controller.initialize();MainPanel panel(&controller);panel.show();QCoreApplication::processEvents();auto *indicator=panel.findChild<QWidget*>(QStringLiteral("inline-processing"));QVERIFY(indicator);panel.setConfigurationBusy(true,L("busy.configuring"),250);QVERIFY(!indicator->isVisible());QTest::qWait(120);panel.setConfigurationBusy(false);QTest::qWait(180);QVERIFY2(!indicator->isVisible(),"A fast operation flashed the delayed processing indicator");panel.setConfigurationBusy(true,L("busy.configuring"),250);QTest::qWait(300);QVERIFY(indicator->isVisible());panel.setConfigurationBusy(false);controller.shutdown();
}

void E2ETests::mouseClicksDoNotLeaveFocusFrames(){
    if(QGuiApplication::platformName()==QStringLiteral("offscreen"))QSKIP("Native mouse focus behavior is required.");QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("focus.ini"))));controller.initialize();controller.settingsFor(QStringLiteral("fake-external")).isEink=true;MainPanel panel(&controller);panel.show();panel.activateWindow();QCoreApplication::processEvents();auto *factory=panel.findChild<QPushButton*>(QStringLiteral("preset-factory"));auto *toggle=panel.findChild<QAbstractButton*>(QStringLiteral("advanced-switch"));QCheckBox *selector=nullptr;for(QCheckBox *box:panel.findChildren<QCheckBox*>(QStringLiteral("eink-checkbox")))if(box->property("displayId").toString()==QStringLiteral("fake-external"))selector=box;QVERIFY(factory);QVERIFY(toggle);QVERIFY(selector);QTest::mouseClick(factory,Qt::LeftButton);QVERIFY(!factory->hasFocus());QTest::mouseClick(toggle,Qt::LeftButton);QVERIFY(!toggle->hasFocus());QTest::mouseClick(selector,Qt::LeftButton);QVERIFY(!selector->hasFocus());factory->setFocus(Qt::TabFocusReason);QVERIFY2(factory->hasFocus(),"Keyboard tab focus was unintentionally removed");controller.shutdown();
}

void E2ETests::mainPanelUsesQtRoundedCorners(){
    QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("corners.ini"))));controller.initialize();MainPanel panel(&controller);panel.show();QCoreApplication::processEvents();QVERIFY(panel.testAttribute(Qt::WA_TranslucentBackground));QVERIFY2(panel.mask().isEmpty(),"Qt rounded corners must not use an aliased window mask");const QImage rendered=panel.grab().toImage().convertToFormat(QImage::Format_ARGB32);QCOMPARE(qAlpha(rendered.pixel(0,0)),0);QCOMPARE(qAlpha(rendered.pixel(rendered.width()-1,0)),0);QCOMPARE(qAlpha(rendered.pixel(0,rendered.height()-1)),0);QCOMPARE(qAlpha(rendered.pixel(rendered.width()-1,rendered.height()-1)),0);QVERIFY(qAlpha(rendered.pixel(rendered.width()/2,rendered.height()/2))>250);QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(panel.grab().save(QStringLiteral("artifacts/e2e-qt-rounded-window.png")));panel.hide();controller.shutdown();
}

void E2ETests::slowSystemTogglesUseLocalSpinner(){QTemporaryDir dir;auto fake=std::make_unique<FakePlatform>();FakePlatform *raw=fake.get();raw->systemDelayMs=350;ApplicationController controller(std::move(fake),SettingsStore(dir.filePath(QStringLiteral("slow-system.ini"))));controller.initialize();MainPanel panel(&controller);panel.show();QCoreApplication::processEvents();auto *visual=panel.findChild<QAbstractButton*>(QStringLiteral("visual-effects-switch"));auto *visualSpinner=panel.findChild<QWidget*>(QStringLiteral("visual-effects-spinner"));auto *visualStatus=panel.findChild<QLabel*>(QStringLiteral("visual-effects-status"));auto *light=panel.findChild<QAbstractButton*>(QStringLiteral("windows-light-mode-switch"));auto *lightSpinner=panel.findChild<QWidget*>(QStringLiteral("windows-light-mode-spinner"));auto *lightStatus=panel.findChild<QLabel*>(QStringLiteral("windows-light-mode-status"));auto *headerBusy=panel.findChild<QWidget*>(QStringLiteral("inline-processing"));QVERIFY(visual);QVERIFY(visualSpinner);QVERIFY(visualStatus);QVERIFY(light);QVERIFY(lightSpinner);QVERIFY(lightStatus);QVERIFY(headerBusy);QElapsedTimer timer;timer.start();visual->click();QCoreApplication::processEvents();QVERIFY2(timer.elapsed()<100,"Visual-effects click blocked the GUI thread.");QVERIFY(!visual->isVisible());QVERIFY(visualSpinner->isVisible());QVERIFY(!headerBusy->isVisible());QDir().mkpath(QStringLiteral("artifacts"));QVERIFY(panel.grab().save(QStringLiteral("artifacts/e2e-local-system-spinner-active.png")));QTest::qWait(300);QVERIFY(!headerBusy->isVisible());QTRY_VERIFY_WITH_TIMEOUT(visual->isVisible(),1000);QVERIFY(!visualSpinner->isVisible());QVERIFY(raw->effectsReduced);QCOMPARE(visualStatus->text(),L("system.on"));timer.restart();light->click();QCoreApplication::processEvents();QVERIFY2(timer.elapsed()<100,"Windows-mode click blocked the GUI thread.");QVERIFY(!light->isVisible());QVERIFY(lightSpinner->isVisible());QVERIFY(!headerBusy->isVisible());QTRY_VERIFY_WITH_TIMEOUT(light->isVisible(),1000);QVERIFY(!lightSpinner->isVisible());QVERIFY(raw->lightMode);QCOMPARE(lightStatus->text(),L("system.on"));QVERIFY(panel.grab().save(QStringLiteral("artifacts/e2e-local-system-spinner.png")));controller.shutdown();}

QTEST_MAIN(E2ETests)
#include "E2ETests.moc"
