#!/usr/bin/env python3
"""Validate reviewed locale catalogs and deterministically build native resources.

English sources are authoritative. Translated catalogs must be complete; English
fallback is a runtime safeguard, never a substitute for a translation at build.
"""
import argparse
from collections import Counter
from html.parser import HTMLParser
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
KINDS = ('app', 'windows', 'site')


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f'duplicate key: {key}')
        result[key] = value
    return result


def read_json(path):
    return json.loads(path.read_text(encoding='utf-8'), object_pairs_hook=unique_object)


class Markup(HTMLParser):
    def __init__(self, value):
        super().__init__(convert_charrefs=True)
        self.events = []
        self.feed(value)
    def handle_starttag(self, tag, attrs):
        self.events.append(('start', tag, sorted(attrs)))
    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)
        if tag not in ('br', 'img', 'hr', 'input', 'meta', 'link'):
            self.handle_endtag(tag)
    def handle_endtag(self, tag):
        self.events.append(('end', tag))


def placeholders(value):
    return Counter(re.findall(r'%(?:\d+\$)?[@dfsu]|%[1-9]\d*(?!\d)', value))


def numeric_values_preserved(english, translated):
    # Localized dates often use numeric months; Japanese also naturally writes
    # English spelled-out counts as digits. Preserve all original numeric data
    # while allowing those explicitly supported word-to-digit conversions.
    pattern = r'[0-9]+(?:\.[0-9]+)*'
    original = Counter(re.findall(pattern, english))
    target = Counter(re.findall(pattern, translated))
    if original - target:
        return False
    words = set(re.findall(r'[a-z]+', english.lower()))
    conversions = {
        'one':'1', 'first':'1', 'once':'1', 'single':'1', 'last':'1',
        'two':'2', 'both':'2', 'second':'2', 'three':'3', 'third':'3',
        'four':'4', 'five':'5', 'six':'6', 'seven':'7', 'eight':'8',
        'nine':'9', 'ten':'10', 'january':'1', 'february':'2', 'march':'3',
        'april':'4', 'may':'5', 'june':'6', 'july':'7', 'august':'8',
        'september':'9', 'october':'10', 'november':'11', 'december':'12',
    }
    allowed = {conversions[word] for word in words if word in conversions}
    return set(target - original).issubset(allowed)


def validate_catalog(source, translated, label):
    errors = []
    missing, extra = set(source) - set(translated), set(translated) - set(source)
    if missing: errors.append(f'{label}: missing keys {sorted(missing)}')
    if extra: errors.append(f'{label}: unknown keys {sorted(extra)}')
    for key in source.keys() & translated.keys():
        en, target = source[key], translated[key]
        if not isinstance(target, str) or not target.strip():
            errors.append(f'{label}:{key}: empty or non-string value')
            continue
        if placeholders(en) != placeholders(target):
            errors.append(f'{label}:{key}: format placeholders differ')
        if not numeric_values_preserved(en, target):
            errors.append(f'{label}:{key}: numeric values or versions differ')
        if Markup(en).events != Markup(target).events:
            errors.append(f'{label}:{key}: HTML tags or attributes differ')
        if Counter(re.findall(r'https?://[^\s<>"\)]+', en)) != Counter(re.findall(r'https?://[^\s<>"\)]+', target)):
            errors.append(f'{label}:{key}: URLs differ')
        if any(0xD800 <= ord(char) <= 0xDFFF for char in target):
            errors.append(f'{label}:{key}: invalid Unicode surrogate')
    return errors


def dump_json(data):
    return json.dumps(data, ensure_ascii=False, indent=2) + '\n'


def strings(catalog):
    quote = lambda s: json.dumps(s, ensure_ascii=False)
    return '/* Generated by scripts/build-localizations.py. Edit localization catalogs. */\n\n' + ''.join(
        f'{quote(key)} = {quote(value)};\n' for key, value in catalog.items())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='validate catalogs and generated resources without writing')
    parser.add_argument('--allow-incomplete', action='store_true', help='development only: skip locales with unfinished catalogs')
    args = parser.parse_args()
    locales = read_json(ROOT / 'localization/locales.json')
    errors = []
    codes = [entry['code'] for entry in locales]
    if len(codes) != 80 or len(set(codes)) != 80: errors.append('Registry must contain exactly 80 unique locales')
    if sum(bool(entry.get('readme')) for entry in locales) != 12: errors.append('Registry must select exactly 12 README locales')
    for entry in locales:
        if not re.fullmatch(r'[a-z]{2,3}(?:-[A-Za-z0-9]{2,8})*', entry['code']): errors.append(f'Invalid locale: {entry}')
        if entry['dir'] not in ('ltr', 'rtl') or not entry['name'].strip(): errors.append(f'Invalid locale metadata: {entry}')
    sources = {kind: read_json(ROOT / f'localization/source/{kind}.en.json') for kind in KINDS}
    planned = {ROOT / 'Resources/locales.json': dump_json(locales)}
    complete = []
    skipped = []
    for entry in locales:
        code = entry['code']
        catalogs = {}
        paths = {kind: ROOT / f'localization/translations/{code}/{kind}.json' for kind in KINDS}
        if code != 'en' and not all(p.exists() for p in paths.values()):
            if args.allow_incomplete:
                skipped.append(code)
                continue
            errors.append(f'{code}: incomplete catalogs')
            continue
        for kind, path in paths.items():
            try:
                catalogs[kind] = sources[kind] if code == 'en' else read_json(path)
                errors.extend(validate_catalog(sources[kind], catalogs[kind], f'{code}/{kind}'))
            except (ValueError, OSError) as error:
                errors.append(f'{path.relative_to(ROOT)}: {error}')
        if len(catalogs) != len(KINDS): continue
        complete.append(code)
        for kind, filename in [('app', 'Localizable.strings'), ('windows', 'Windows.strings')]:
            planned[ROOT / f'Resources/{code}.lproj/{filename}'] = strings(catalogs[kind])
    if errors:
        print('\n'.join(errors), file=sys.stderr)
        return 1
    for path, content in planned.items():
        if args.check:
            if not path.exists() or path.read_text() != content: errors.append(f'Stale generated resource: {path.relative_to(ROOT)}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
    if errors:
        print('\n'.join(errors), file=sys.stderr)
        return 1
    print(f'{len(complete)}/80 locales validated; 117 shared app keys, 40 Windows keys, {len(sources["site"])} website keys each.')
    if skipped: print('INCOMPLETE (development run): ' + ', '.join(skipped))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
